
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontology-manager-deployment
  namespace: on-man
  labels:
    app: ontology-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontology-manager
  template:
    metadata:
      labels:
        app: ontology-manager  
    spec:
      containers: 
      - name: ontology-manager 
        image: desourav0607/on-man:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: ontology-manager-service
  namespace: on-man
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: ontology-manager